version: '3.7'

services:
  web:
    build: .
    container_name: booking_app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    restart: always
