global:
  scrape_interval: 5m     # Сбор метрик каждые 5 минут
  evaluation_interval: 5m

scrape_configs:
  - job_name: 'system'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx'
    scheme: https    # Указываем схему https
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:443']  # Меняем порт на 443
    tls_config:
      insecure_skip_verify: true    # Для локального мониторинга можно пропустить проверку сертификата

  - job_name: 'flask'
    metrics_path: '/flask-health-check'
    static_configs:
      - targets: ['localhost:8000']