filenames:
  - /var/log/nginx/access.log
  - /var/log/nginx/error.log
labels:
  type: nginx

scenarios:
  - crowdsecurity/http-crawl-non_statics
  - crowdsecurity/http-probing
  - crowdsecurity/http-bad-user-agent
  - crowdsecurity/http-path-traversal-probing
  - crowdsecurity/http-xss-probing
  - crowdsecurity/http-sqli-probing

parsers:
  - crowdsecurity/nginx-logs
  - crowdsecurity/http-logs
  - crowdsecurity/whitelists
  - crowdsecurity/dateparse-enrich