api:
  server:
    listen_uri: 127.0.0.1:8080
    profiles_path: /etc/crowdsec/profiles.yaml
  client:
    credentials_path: /etc/crowdsec/local_api_credentials.yaml

capi:
  url: https://api.crowdsec.net/
  login: ${CROWDSEC_API_KEY}  # API https://app.crowdsec.net
common:
  daemonize: false
  pid_dir: /var/run/
  log_media: file
  log_level: info
  log_dir: /var/log/
  working_dir: /var/lib/crowdsec/data/

config_paths:
  config_dir: /etc/crowdsec/
  data_dir: /var/lib/crowdsec/data/

crowdsec_service:
  acquisition_path: /etc/crowdsec/acquis.yaml
  parser_routines: 1

api:
  server:
    listen_uri: 127.0.0.1:8080
    profiles_path: /etc/crowdsec/profiles.yaml

db_config:
  type: sqlite
  db_path: /var/lib/crowdsec/data/crowdsec.db

acquisition:
  file:
    - filename: /var/log/nginx/access.log
      labels:
        type: nginx
    - filename: /var/log/nginx/error.log
      labels:
        type: nginx-error