name: Deploy Nginx to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

    - name: Copy Dockerfile to AWS
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa Dockerfile ${{ secrets.SERVER_USER }}@${{ secrets.AWS_SERVER_IP }}:~/

    - name: Connect to AWS and deploy Nginx
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.AWS_SERVER_IP }} << EOF
          # Убедимся, что Docker установлен
          sudo apt-get update && sudo apt-get install -y docker.io

          # Удаляем старые контейнеры и образы
          sudo docker stop nginx || true
          sudo docker rm nginx || true
          sudo docker rmi nginx:latest || true

          # Собираем новый образ и запускаем контейнер
          sudo docker build -t nginx:latest .
          sudo docker run -d --name nginx -p 80:80 nginx:latest
        EOF
