name: Deploy to AWS and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker-compose build

    - name: Push Flask Docker Image to Docker Hub
      run: |
        docker tag flask_app ${{ secrets.DOCKER_USERNAME }}/booking_app:flask
        docker push ${{ secrets.DOCKER_USERNAME }}/booking_app:flask

    - name: Push Nginx Docker Image to Docker Hub
      run: |
        docker tag nginx ${{ secrets.DOCKER_USERNAME }}/booking_app:nginx
        docker push ${{ secrets.DOCKER_USERNAME }}/booking_app:nginx

    - name: Deploy to AWS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          sudo apt update
          sudo apt install -y docker.io docker-compose

          docker-compose down || true
          docker-compose pull
          docker-compose up -d
