name: Deploy Nginx to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout кода
    - name: Checkout code
      uses: actions/checkout@v3

    # Вход в DockerHub (если требуется)
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Сборка Docker-образа
    - name: Build Docker image
      run: docker build -t my-nginx .

    # Отправка образа в DockerHub (опционально)
    - name: Push Docker image
      run: docker push my-nginx:latest

    # Развертывание на сервере AWS
    - name: Deploy to AWS
      env:
        AWS_SERVER_IP: ${{ secrets.AWS_SERVER_IP }}
        AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "${{ secrets.AWS_SSH_KEY }}" > aws_key.pem
        chmod 600 aws_key.pem
        ssh -o StrictHostKeyChecking=no -i aws_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.AWS_SERVER_IP }} << EOF
          docker pull my-nginx:latest
          docker stop nginx || true
          docker rm nginx || true
          docker run -d --name nginx -p 80:80 my-nginx:latest
        EOF
