name: Website Health Check

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:

      - name: Get current IP address for GitHub Actions
        id: get_ip
        run: |
          IP=$(curl -s https://api.ipify.org)
          echo "Current IP: $IP"
          echo "IP=$IP" >> $GITHUB_ENV

      - name: Add IP for GitHub Actions to Cloudflare whitelist
        env:
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/firewall/access_rules/rules" \
            -H "Authorization: Bearer $CLOUDFLARE_API_KEY" \
            -H "Content-Type: application/json" \
            --data '{
              "mode":"whitelist",
              "configuration":{"target":"ip","value":"'"$IP"'"},
              "notes":"Allow GitHub Actions runner"
            }'

      - name: Check Website Health
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://bbooking.pp.ua/health-check)
          if [ "$response" != "200" ]; then
            echo "Website health check failed! Status code: $response"
            exit 1
          fi
          echo "Website health check passed"
