name: Intrusion Prevention System Workflow

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Monitoring Intrusion Prevention System Efficiency'
        required: false
        default: 'Should be manually triggered'
  
jobs:
  ips-settings-monitoring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: SSH and Fail2Ban Status Check
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |

            # Fail2Ban Status
            echo "Fail2Ban status:"
            systemctl status fail2ban | grep -E 'Active|Loaded|Main PID'
            echo "**************************************************************************************************"

            # Fail2Ban Status for sshd-custom jail
            echo "Current Fail2Ban status for sshd-custom:"
            sudo fail2ban-client status sshd-custom
            echo "**************************************************************************************************"

            # Fail2Ban Status for nginx-direct-ip jail
            echo "Current Fail2Ban status for nginx-direct-ip:"
            sudo fail2ban-client status nginx-direct-ip            
            


      - name: Check Cloudflare Security Level
        run: |
          RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/settings/security_level" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_KEY }}" \
            -H "Content-Type: application/json")
          
          SECURITY_LEVEL=$(echo $RESPONSE | jq -r '.result.value')
          MODIFIED_DATE=$(echo $RESPONSE | jq -r '.result.modified_on')
          
          echo "Security Level: $SECURITY_LEVEL"
          echo "Modified: $MODIFIED_DATE"

